import { createFileRoute, Link } from '@tanstack/react-router'
import { ChevronLeft } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { LandingFooter } from '@/components/landing/LandingFooter'

export const Route = createFileRoute('/privacy')({
  component: PrivacyPage,
})

function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Back Button */}
      <div className="fixed top-4 left-4 md:top-8 md:left-8 z-50">
        <Link to="/">
          <Button
            variant="outline"
            className="gap-2 bg-white/80 backdrop-blur-sm border-slate-200 text-slate-600 hover:text-slate-900 hover:bg-white shadow-sm"
          >
            <ChevronLeft className="h-4 w-4" />
            Back to Home
          </Button>
        </Link>
      </div>

      {/* Content */}
      <main className="container mx-auto px-4 lg:px-8 pt-24 pb-16 lg:pt-32 lg:pb-24">
        <div className="max-w-3xl mx-auto">
          {/* Header */}
          <div className="mb-12">
            <h1 className="text-3xl md:text-4xl font-bold tracking-tight text-slate-900 mb-4">
              Privacy Policy
            </h1>
            <p className="text-slate-500">Last updated: January 12, 2026</p>
          </div>

          {/* Legal Content */}
          <div className="prose prose-slate max-w-none prose-headings:text-slate-900 prose-p:text-slate-600 prose-li:text-slate-600 prose-a:text-[#5a7ba6] hover:prose-a:text-[#7e9ec9] prose-strong:text-slate-700">
            {/* 1. Introduction */}
            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 mb-4 pb-2 border-b border-slate-200">
                1. Introduction
              </h2>
              <p>
                Welcome to Memdia. This Privacy Policy explains how Memdia,
                operated by Hakan Bilgic ("we," "us," or "our"), collects, uses,
                discloses, and protects your personal information when you use
                our voice AI companion application and related services
                (collectively, the "Service").
              </p>
              <p>
                Memdia is a voice AI daily companion application designed to
                help you with daily check-ins, therapeutic reflection
                conversations, and personal growth insights. Our Service
                processes voice recordings, generates transcripts, analyzes
                moods and topics, and provides AI-generated insights to support
                your wellbeing journey.
              </p>
              <p>
                By using our Service, you agree to the collection and use of
                information in accordance with this Privacy Policy. If you do
                not agree with our policies and practices, please do not use our
                Service.
              </p>
            </section>

            {/* 2. Information We Collect */}
            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 mb-4 pb-2 border-b border-slate-200">
                2. Information We Collect
              </h2>

              <h3 className="text-lg font-medium text-slate-800 mt-6 mb-3">
                2.1 Account Information
              </h3>
              <p>When you create an account, we collect:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Email address</li>
                <li>Name (if provided)</li>
                <li>Profile information (avatar, preferences)</li>
                <li>Authentication credentials (encrypted)</li>
                <li>
                  Google account information (if you sign up via Google OAuth)
                </li>
              </ul>

              <h3 className="text-lg font-medium text-slate-800 mt-6 mb-3">
                2.2 Voice and Conversation Data
              </h3>
              <p>When you use our voice features, we collect and process:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong>Voice Recordings:</strong> Audio recordings from your
                  voice sessions and reflection sessions
                </li>
                <li>
                  <strong>Transcripts:</strong> Text transcriptions of your
                  voice recordings generated through speech-to-text processing
                </li>
                <li>
                  <strong>AI-Generated Content:</strong> Responses, summaries,
                  and images generated by our AI systems based on your
                  conversations
                </li>
                <li>
                  <strong>Session Metadata:</strong> Duration, timestamps, and
                  session type information
                </li>
              </ul>

              <h3 className="text-lg font-medium text-slate-800 mt-6 mb-3">
                2.3 Reflection and Insight Data
              </h3>
              <p>From your reflection sessions, we extract and store:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong>Mood Data:</strong> Detected emotional states and mood
                  patterns
                </li>
                <li>
                  <strong>Topics:</strong> Subjects and themes discussed in your
                  sessions
                </li>
                <li>
                  <strong>Insights:</strong> AI-generated observations about
                  patterns in your reflections
                </li>
                <li>
                  <strong>Personal References:</strong> Names and relationships
                  mentioned (to provide contextual responses)
                </li>
                <li>
                  <strong>To-Do Items:</strong> Tasks and action items extracted
                  from conversations
                </li>
              </ul>

              <h3 className="text-lg font-medium text-slate-800 mt-6 mb-3">
                2.4 Usage and Technical Data
              </h3>
              <p>We automatically collect:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Device information (browser type, operating system)</li>
                <li>IP address and approximate location</li>
                <li>Usage patterns (features used, session frequency)</li>
                <li>Error logs and performance data</li>
                <li>Cookies and similar tracking technologies</li>
              </ul>

              <h3 className="text-lg font-medium text-slate-800 mt-6 mb-3">
                2.5 Payment Information
              </h3>
              <p>
                If you subscribe to our paid services, payment processing is
                handled by Stripe. We do not store your full credit card
                numbers. We receive from Stripe:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Transaction confirmations and subscription status</li>
                <li>
                  Last four digits of your payment method (for display purposes)
                </li>
                <li>Billing address (if provided)</li>
              </ul>
            </section>

            {/* 3. How We Use Your Information */}
            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 mb-4 pb-2 border-b border-slate-200">
                3. How We Use Your Information
              </h2>
              <p>We use your information for the following purposes:</p>

              <h3 className="text-lg font-medium text-slate-800 mt-6 mb-3">
                3.1 Service Delivery
              </h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>Process your voice recordings and generate transcripts</li>
                <li>Provide AI-powered conversation responses</li>
                <li>
                  Generate personalized insights, mood tracking, and topic
                  analysis
                </li>
                <li>Create AI-generated images summarizing your sessions</li>
                <li>Deliver daily greetings and personalized content</li>
              </ul>

              <h3 className="text-lg font-medium text-slate-800 mt-6 mb-3">
                3.2 Personalization
              </h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>Remember context from previous conversations</li>
                <li>Track your personal growth over time</li>
                <li>
                  Customize AI responses based on your history and preferences
                </li>
                <li>
                  Provide the Service in your preferred language (32 languages
                  supported)
                </li>
              </ul>

              <h3 className="text-lg font-medium text-slate-800 mt-6 mb-3">
                3.3 Service Improvement
              </h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>Analyze usage patterns to improve features</li>
                <li>Debug and fix technical issues</li>
                <li>Develop new features and services</li>
              </ul>

              <h3 className="text-lg font-medium text-slate-800 mt-6 mb-3">
                3.4 Communication
              </h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>Send service-related notifications</li>
                <li>Respond to your inquiries and support requests</li>
                <li>Notify you of changes to our policies or services</li>
              </ul>

              <h3 className="text-lg font-medium text-slate-800 mt-6 mb-3">
                3.5 Legal and Safety
              </h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>Comply with legal obligations</li>
                <li>Enforce our Terms of Service</li>
                <li>Protect against fraud, abuse, and security threats</li>
              </ul>
            </section>

            {/* 4. Legal Basis for Processing (GDPR) */}
            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 mb-4 pb-2 border-b border-slate-200">
                4. Legal Basis for Processing (GDPR)
              </h2>
              <p>
                If you are located in the European Economic Area (EEA), United
                Kingdom, or Turkey, we process your personal data based on the
                following legal grounds:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong>Contract Performance:</strong> Processing necessary to
                  provide you with the Service as described in our Terms of
                  Service.
                </li>
                <li>
                  <strong>Consent:</strong> Where you have given explicit
                  consent for specific processing activities, such as voice
                  recording and AI analysis.
                </li>
                <li>
                  <strong>Legitimate Interests:</strong> Processing necessary
                  for our legitimate business interests, such as improving the
                  Service, provided these interests do not override your rights.
                </li>
                <li>
                  <strong>Legal Obligation:</strong> Processing necessary to
                  comply with applicable laws and regulations.
                </li>
              </ul>
            </section>

            {/* 5. Data Storage and Security */}
            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 mb-4 pb-2 border-b border-slate-200">
                5. Data Storage and Security
              </h2>
              <p>
                We implement appropriate technical and organizational measures
                to protect your data:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong>Database Security:</strong> Your account and session
                  data is stored in encrypted databases with access controls.
                </li>
                <li>
                  <strong>Audio Storage:</strong> Voice recordings are stored on
                  secure content delivery networks (CDN) with encryption at rest
                  and in transit.
                </li>
                <li>
                  <strong>Transmission Security:</strong> All data transmitted
                  between your device and our servers is encrypted using TLS/SSL
                  protocols.
                </li>
                <li>
                  <strong>Access Controls:</strong> Access to personal data is
                  restricted to authorized personnel who need it to operate,
                  develop, or improve our Service.
                </li>
                <li>
                  <strong>Authentication:</strong> We use secure authentication
                  methods including encrypted password storage and OAuth 2.0 for
                  third-party authentication.
                </li>
              </ul>
              <p className="mt-4">
                While we strive to protect your personal information, no method
                of transmission over the Internet or electronic storage is 100%
                secure. We cannot guarantee absolute security.
              </p>
            </section>

            {/* 6. Third-Party Service Providers */}
            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 mb-4 pb-2 border-b border-slate-200">
                6. Third-Party Service Providers
              </h2>
              <p>
                We use third-party services to provide and improve our Service.
                These providers have access to your personal information only to
                perform specific tasks on our behalf and are obligated to
                protect your data:
              </p>

              <div className="mt-4 space-y-4">
                <div className="p-4 bg-slate-50 rounded-lg border border-slate-200">
                  <h4 className="font-medium text-slate-800">
                    Deepgram (Speech-to-Text)
                  </h4>
                  <p className="text-sm text-slate-600 mt-1">
                    Processes your voice recordings to generate text
                    transcripts. Located in the United States.
                  </p>
                </div>

                <div className="p-4 bg-slate-50 rounded-lg border border-slate-200">
                  <h4 className="font-medium text-slate-800">
                    OpenRouter (AI Language Models)
                  </h4>
                  <p className="text-sm text-slate-600 mt-1">
                    Powers our AI conversation capabilities and generates
                    responses. Located in the United States.
                  </p>
                </div>

                <div className="p-4 bg-slate-50 rounded-lg border border-slate-200">
                  <h4 className="font-medium text-slate-800">
                    Fal.ai (Image Generation)
                  </h4>
                  <p className="text-sm text-slate-600 mt-1">
                    Creates AI-generated images summarizing your voice sessions.
                    Located in the United States.
                  </p>
                </div>

                <div className="p-4 bg-slate-50 rounded-lg border border-slate-200">
                  <h4 className="font-medium text-slate-800">
                    Bunny CDN (Audio Storage)
                  </h4>
                  <p className="text-sm text-slate-600 mt-1">
                    Stores and delivers your audio recordings securely. Global
                    CDN with European presence.
                  </p>
                </div>

                <div className="p-4 bg-slate-50 rounded-lg border border-slate-200">
                  <h4 className="font-medium text-slate-800">
                    Stripe (Payment Processing)
                  </h4>
                  <p className="text-sm text-slate-600 mt-1">
                    Handles subscription payments and billing. PCI-DSS
                    compliant. Located in the United States.
                  </p>
                </div>

                <div className="p-4 bg-slate-50 rounded-lg border border-slate-200">
                  <h4 className="font-medium text-slate-800">
                    Google (Authentication)
                  </h4>
                  <p className="text-sm text-slate-600 mt-1">
                    Provides optional OAuth authentication for account creation.
                    Located in the United States.
                  </p>
                </div>
              </div>
            </section>

            {/* 7. International Data Transfers */}
            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 mb-4 pb-2 border-b border-slate-200">
                7. International Data Transfers
              </h2>
              <p>
                Your information may be transferred to and processed in
                countries other than your country of residence, particularly the
                United States, where many of our third-party service providers
                are located.
              </p>
              <p className="mt-4">
                When we transfer personal data outside the European Economic
                Area (EEA), United Kingdom, or Turkey, we ensure appropriate
                safeguards are in place, including:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  Standard Contractual Clauses approved by the European
                  Commission
                </li>
                <li>Adequacy decisions where applicable</li>
                <li>Binding corporate rules of our service providers</li>
                <li>Your explicit consent for specific transfers</li>
              </ul>
              <p className="mt-4">
                By using our Service, you acknowledge and consent to the
                transfer of your information to countries outside your
                residence, including the United States.
              </p>
            </section>

            {/* 8. Your Rights */}
            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 mb-4 pb-2 border-b border-slate-200">
                8. Your Rights
              </h2>
              <p>
                Under the General Data Protection Regulation (GDPR) and other
                applicable data protection laws, you have the following rights
                regarding your personal data:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong>Right of Access:</strong> You can request a copy of
                  the personal data we hold about you.
                </li>
                <li>
                  <strong>Right to Rectification:</strong> You can request
                  correction of inaccurate or incomplete personal data.
                </li>
                <li>
                  <strong>Right to Erasure ("Right to be Forgotten"):</strong>{' '}
                  You can request deletion of your personal data, subject to
                  certain legal exceptions.
                </li>
                <li>
                  <strong>Right to Data Portability:</strong> You can request
                  your data in a structured, commonly used, machine-readable
                  format.
                </li>
                <li>
                  <strong>Right to Restrict Processing:</strong> You can request
                  that we limit how we use your data in certain circumstances.
                </li>
                <li>
                  <strong>Right to Object:</strong> You can object to processing
                  based on legitimate interests or for direct marketing
                  purposes.
                </li>
                <li>
                  <strong>Right to Withdraw Consent:</strong> Where processing
                  is based on consent, you can withdraw your consent at any
                  time.
                </li>
                <li>
                  <strong>Right to Lodge a Complaint:</strong> You can file a
                  complaint with a supervisory authority if you believe your
                  rights have been violated.
                </li>
              </ul>
              <p className="mt-4">
                To exercise any of these rights, please contact us at{' '}
                <a
                  href="mailto:hbilgic1992@gmail.com"
                  className="text-[#5a7ba6] hover:text-[#7e9ec9]"
                >
                  hbilgic1992@gmail.com
                </a>
                . We will respond to your request within 30 days.
              </p>
            </section>

            {/* 9. Data Retention */}
            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 mb-4 pb-2 border-b border-slate-200">
                9. Data Retention
              </h2>
              <p>We retain your personal data as follows:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong>Active Accounts:</strong> We retain your data for as
                  long as your account is active and as needed to provide you
                  with the Service.
                </li>
                <li>
                  <strong>Voice Recordings:</strong> Stored until you delete
                  them or delete your account. You can delete individual
                  recordings at any time through the Service.
                </li>
                <li>
                  <strong>Account Deletion:</strong> When you delete your
                  account, we retain your data for 30 days to allow for account
                  recovery. After this period, your data is permanently deleted
                  from our systems.
                </li>
                <li>
                  <strong>Backups:</strong> Data may persist in encrypted
                  backups for up to 90 days after deletion for disaster recovery
                  purposes, after which it is permanently removed.
                </li>
                <li>
                  <strong>Legal Requirements:</strong> We may retain certain
                  information longer if required by law or to protect our legal
                  rights.
                </li>
              </ul>
            </section>

            {/* 10. Children's Privacy */}
            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 mb-4 pb-2 border-b border-slate-200">
                10. Children's Privacy
              </h2>
              <p>
                Our Service is not intended for individuals under the age of 16.
                We do not knowingly collect personal information from children
                under 16 years of age.
              </p>
              <p className="mt-4">
                If you are a parent or guardian and you become aware that your
                child has provided us with personal information without your
                consent, please contact us at{' '}
                <a
                  href="mailto:hbilgic1992@gmail.com"
                  className="text-[#5a7ba6] hover:text-[#7e9ec9]"
                >
                  hbilgic1992@gmail.com
                </a>
                . If we become aware that we have collected personal information
                from a child under 16, we will take steps to delete that
                information promptly.
              </p>
            </section>

            {/* 11. Cookies and Tracking Technologies */}
            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 mb-4 pb-2 border-b border-slate-200">
                11. Cookies and Tracking Technologies
              </h2>
              <p>We use cookies and similar technologies to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong>Essential Cookies:</strong> Required for the Service
                  to function, including authentication and session management.
                </li>
                <li>
                  <strong>Preference Cookies:</strong> Remember your settings
                  and preferences (e.g., language selection).
                </li>
                <li>
                  <strong>Analytics Cookies:</strong> Help us understand how you
                  use the Service to improve user experience.
                </li>
              </ul>
              <p className="mt-4">
                You can control cookies through your browser settings. Note that
                disabling certain cookies may affect the functionality of the
                Service.
              </p>
            </section>

            {/* 12. Changes to This Privacy Policy */}
            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 mb-4 pb-2 border-b border-slate-200">
                12. Changes to This Privacy Policy
              </h2>
              <p>
                We may update this Privacy Policy from time to time. We will
                notify you of any material changes by:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Posting the new Privacy Policy on this page</li>
                <li>
                  Updating the "Last updated" date at the top of this Policy
                </li>
                <li>
                  Sending you an email notification for significant changes (if
                  you have an account)
                </li>
              </ul>
              <p className="mt-4">
                We encourage you to review this Privacy Policy periodically for
                any changes. Your continued use of the Service after changes are
                posted constitutes your acceptance of the updated Privacy
                Policy.
              </p>
            </section>

            {/* 13. Contact Information */}
            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 mb-4 pb-2 border-b border-slate-200">
                13. Contact Information
              </h2>
              <p>
                If you have any questions, concerns, or requests regarding this
                Privacy Policy or our data practices, please contact us:
              </p>
              <div className="mt-4 p-6 bg-slate-50 rounded-lg border border-slate-200">
                <p className="font-medium text-slate-800">Memdia</p>
                <p className="text-slate-600 mt-2">Operated by Hakan Bilgic</p>
                <p className="text-slate-600 mt-2">
                  Email:{' '}
                  <a
                    href="mailto:hbilgic1992@gmail.com"
                    className="text-[#5a7ba6] hover:text-[#7e9ec9]"
                  >
                    hbilgic1992@gmail.com
                  </a>
                </p>
              </div>
              <p className="mt-4">
                We will make every effort to respond to your inquiry within 30
                days.
              </p>
            </section>
          </div>
        </div>
      </main>

      <LandingFooter />
    </div>
  )
}
