/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppReflectionsRouteImport } from './routes/_app/reflections'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppMemoriesRouteImport } from './routes/_app/memories'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as ApiStreamConversationRouteImport } from './routes/api/stream/conversation'
import { Route as ApiStreamCancelRouteImport } from './routes/api/stream/cancel'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppReflectionsTodayRouteImport } from './routes/_app/reflections.today'
import { Route as AppReflectionsDateRouteImport } from './routes/_app/reflections.$date'
import { Route as AppMemoriesTodayRouteImport } from './routes/_app/memories.today'
import { Route as AppMemoriesDateRouteImport } from './routes/_app/memories.$date'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppReflectionsRoute = AppReflectionsRouteImport.update({
  id: '/reflections',
  path: '/reflections',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoriesRoute = AppMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiStreamConversationRoute = ApiStreamConversationRouteImport.update({
  id: '/api/stream/conversation',
  path: '/api/stream/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamCancelRoute = ApiStreamCancelRouteImport.update({
  id: '/api/stream/cancel',
  path: '/api/stream/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReflectionsTodayRoute = AppReflectionsTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppReflectionsRoute,
} as any)
const AppReflectionsDateRoute = AppReflectionsDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => AppReflectionsRoute,
} as any)
const AppMemoriesTodayRoute = AppMemoriesTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppMemoriesRoute,
} as any)
const AppMemoriesDateRoute = AppMemoriesDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => AppMemoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/memories': typeof AppMemoriesRouteWithChildren
  '/onboarding': typeof AppOnboardingRoute
  '/profile': typeof AppProfileRoute
  '/reflections': typeof AppReflectionsRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/memories/$date': typeof AppMemoriesDateRoute
  '/memories/today': typeof AppMemoriesTodayRoute
  '/reflections/$date': typeof AppReflectionsDateRoute
  '/reflections/today': typeof AppReflectionsTodayRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stream/cancel': typeof ApiStreamCancelRoute
  '/api/stream/conversation': typeof ApiStreamConversationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/memories': typeof AppMemoriesRouteWithChildren
  '/onboarding': typeof AppOnboardingRoute
  '/profile': typeof AppProfileRoute
  '/reflections': typeof AppReflectionsRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/memories/$date': typeof AppMemoriesDateRoute
  '/memories/today': typeof AppMemoriesTodayRoute
  '/reflections/$date': typeof AppReflectionsDateRoute
  '/reflections/today': typeof AppReflectionsTodayRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stream/cancel': typeof ApiStreamCancelRoute
  '/api/stream/conversation': typeof ApiStreamConversationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/pricing': typeof PricingRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/memories': typeof AppMemoriesRouteWithChildren
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reflections': typeof AppReflectionsRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/memories/$date': typeof AppMemoriesDateRoute
  '/_app/memories/today': typeof AppMemoriesTodayRoute
  '/_app/reflections/$date': typeof AppReflectionsDateRoute
  '/_app/reflections/today': typeof AppReflectionsTodayRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stream/cancel': typeof ApiStreamCancelRoute
  '/api/stream/conversation': typeof ApiStreamConversationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/admin'
    | '/dashboard'
    | '/memories'
    | '/onboarding'
    | '/profile'
    | '/reflections'
    | '/login'
    | '/signup'
    | '/memories/$date'
    | '/memories/today'
    | '/reflections/$date'
    | '/reflections/today'
    | '/api/auth/$'
    | '/api/stream/cancel'
    | '/api/stream/conversation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/admin'
    | '/dashboard'
    | '/memories'
    | '/onboarding'
    | '/profile'
    | '/reflections'
    | '/login'
    | '/signup'
    | '/memories/$date'
    | '/memories/today'
    | '/reflections/$date'
    | '/reflections/today'
    | '/api/auth/$'
    | '/api/stream/cancel'
    | '/api/stream/conversation'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/pricing'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/memories'
    | '/_app/onboarding'
    | '/_app/profile'
    | '/_app/reflections'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/memories/$date'
    | '/_app/memories/today'
    | '/_app/reflections/$date'
    | '/_app/reflections/today'
    | '/api/auth/$'
    | '/api/stream/cancel'
    | '/api/stream/conversation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PricingRoute: typeof PricingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStreamCancelRoute: typeof ApiStreamCancelRoute
  ApiStreamConversationRoute: typeof ApiStreamConversationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/reflections': {
      id: '/_app/reflections'
      path: '/reflections'
      fullPath: '/reflections'
      preLoaderRoute: typeof AppReflectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memories': {
      id: '/_app/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof AppMemoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/stream/conversation': {
      id: '/api/stream/conversation'
      path: '/api/stream/conversation'
      fullPath: '/api/stream/conversation'
      preLoaderRoute: typeof ApiStreamConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/cancel': {
      id: '/api/stream/cancel'
      path: '/api/stream/cancel'
      fullPath: '/api/stream/cancel'
      preLoaderRoute: typeof ApiStreamCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/reflections/today': {
      id: '/_app/reflections/today'
      path: '/today'
      fullPath: '/reflections/today'
      preLoaderRoute: typeof AppReflectionsTodayRouteImport
      parentRoute: typeof AppReflectionsRoute
    }
    '/_app/reflections/$date': {
      id: '/_app/reflections/$date'
      path: '/$date'
      fullPath: '/reflections/$date'
      preLoaderRoute: typeof AppReflectionsDateRouteImport
      parentRoute: typeof AppReflectionsRoute
    }
    '/_app/memories/today': {
      id: '/_app/memories/today'
      path: '/today'
      fullPath: '/memories/today'
      preLoaderRoute: typeof AppMemoriesTodayRouteImport
      parentRoute: typeof AppMemoriesRoute
    }
    '/_app/memories/$date': {
      id: '/_app/memories/$date'
      path: '/$date'
      fullPath: '/memories/$date'
      preLoaderRoute: typeof AppMemoriesDateRouteImport
      parentRoute: typeof AppMemoriesRoute
    }
  }
}

interface AppMemoriesRouteChildren {
  AppMemoriesDateRoute: typeof AppMemoriesDateRoute
  AppMemoriesTodayRoute: typeof AppMemoriesTodayRoute
}

const AppMemoriesRouteChildren: AppMemoriesRouteChildren = {
  AppMemoriesDateRoute: AppMemoriesDateRoute,
  AppMemoriesTodayRoute: AppMemoriesTodayRoute,
}

const AppMemoriesRouteWithChildren = AppMemoriesRoute._addFileChildren(
  AppMemoriesRouteChildren,
)

interface AppReflectionsRouteChildren {
  AppReflectionsDateRoute: typeof AppReflectionsDateRoute
  AppReflectionsTodayRoute: typeof AppReflectionsTodayRoute
}

const AppReflectionsRouteChildren: AppReflectionsRouteChildren = {
  AppReflectionsDateRoute: AppReflectionsDateRoute,
  AppReflectionsTodayRoute: AppReflectionsTodayRoute,
}

const AppReflectionsRouteWithChildren = AppReflectionsRoute._addFileChildren(
  AppReflectionsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMemoriesRoute: typeof AppMemoriesRouteWithChildren
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReflectionsRoute: typeof AppReflectionsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMemoriesRoute: AppMemoriesRouteWithChildren,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRoute,
  AppReflectionsRoute: AppReflectionsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PricingRoute: PricingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStreamCancelRoute: ApiStreamCancelRoute,
  ApiStreamConversationRoute: ApiStreamConversationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
